Income:
  - DIRECT DEP SONY

Revenue:
  - MOBILE DEPOSIT

Utilities:
  - DUKEENERGY
  - DOMINION ENERGY
  - UTIL PAYMT
  - VERIZON WIRELESS
  - WAKE PRO LAWN CARE
  - SPECTRUM
  - PIEDMONT ELECTRIC

Food Restaurants:
  - CARRBURRITOS
  - TACO BELL
  - CHICK\-FIL\-A
  - TENKO JAPAN
  - AMANTEGOURMET
  - FIREHOUSE SUBS
  - WHICH WICH
  - TOWN HALL BURGER
  - PEOPLE'S COFFEE
  - TA CONTENTO
  - CARRBORO CARRBORO

Food Alcohol & Bars:
  - TST\* MOTORCO

Food Groceries:
  - WEGMANS
  - HARRIS TEETER
  - LOWES FOODS

Food:
  ~

Subscriptions:
  - GITHUB

Entertainment:
  - NINTENDO INTERNATIONAL
  - MOTORCOMUSIC.COM

Entertainment Subscriptions:
  - DISNEY PLUS
  - YOUTUBEINTERNET
  - SPOTIFYUSA
  - CRUNCHYROLL
  - NETFLIX.COM
  - PATREON

Hobbies:
  - HANGAR 18

Gas:
  - CIRCLE K
  - REFUEL

Car Expenses:
  ~

Home Maintenance:
  - Jose Garcia
  - Joel Lloyd

Home Repairs:
  - WESTLAKE HARDWARE
  - LOWE'S OF PITTSBORO
  - CABINETPART
  - T\&C \- CHATHAM DOWNS

Home:
  ~

Home Improvement:
  - WAYFAIR

Pets:
  - KINDRED HEART

Medical:
  - DERMATOLOGY

Shopping:
  - AMAZON MKTPL

Retirement:
  - EDWARD JONES
  - INTEREST PAYMENT

Transfer:
  - TRUIST ONLINE TRANSFER
  - TRUIST DEPOSIT TRANSFER
  

Credit Card Payment:
  - E\-PAYMENT DISCOVER
  - DIRECTPAY FULL BALANCE

Big Purchases:
  ~

Gifts:
  ~

Loans:
  ~